### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by shlomiken** [nokia/kong-oidc#45]
Hi 
i'm preparing a docker image that contains OIDC plugin and the luarocks fails to install the rock.
any help would be appreciated.
Shlomi
Warning: Failed searching manifest: Failed extracting manifest file
Installing https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/kong-oidc-1.0.4-0.src.rock

**Comment by shlomiken** [comment]
Hi 
i installed unzip , now i got this (openssl headers)
lua-resty-openidc 1.4.0-1 depends on lua-resty-hmac (not installed)
Installing https://luarocks.org/lua-resty-hmac-v1.0-1.rockspec
Missing dependencies for lua-resty-hmac v1.0-1:
   luacrypto (not installed)

lua-resty-hmac v1.0-1 depends on luacrypto (not installed)
Installing https://luarocks.org/luacrypto-0.3.2-2.src.rock

Error: Failed installing dependency: https://luarocks.org/lua-resty-openidc-1.4.0-1.src.rock - Failed installing dependency: https://luarocks.org/lua-resty-hmac-v1.0-1.rockspec - Failed installing dependency: https://luarocks.org/luacrypto-0.3.2-2.src.rock - Could not find header file for OPENSSL
  No file openssl/evp.h in /usr/local/include
  No file openssl/evp.h in /usr/include
You may have to install OPENSSL in your system and/or pass OPENSSL_DIR or OPENSSL_INCDIR to the luarocks command.
Example: luarocks install luacrypto OPENSSL_DIR=/usr/local
sh-4.2#

**Comment by shlomiken** [comment]
i also see that in the kong docker luassl is already installed , while this library dependent somehow on 
luacrypto - which fail to compile.

**Comment by Trojan295** [comment]
Can you try to install OpenSSL development package `libssl-dev`?

**Comment by shlomiken** [comment]
i did (both sslib-dev and openssl-devel) none did work.
the problem is that openrest works with openssl 1.0 (i believe) and i have openssl 1.1

after installing devel - i get this compilation error.
Error: Failed installing dependency: https://luarocks.org/lua-resty-openidc-1.4.0-1.src.rock - Failed installing dependency: https://luarocks.org/lua-resty-hmac-v1.0-1.rockspec - Failed installing dependency: https://luarocks.org/luacrypto-0.3.2-2.src.rock - Build error: Failed compiling object src/lcrypto.o

**Comment by Trojan295** [comment]
I got it working by installing the following packages before installing kong-oidc:
```
RUN apk add gcc libc-dev git openssl-dev
```
I believe you can remove `gcc` and `git` at the end of the Dockerfile to save space.

**Comment by shlomiken** [comment]
this is what i get on the instance of docker (alpine latest)
/ # apk add gcc libc-dev git openssl-dev
WARNING: Ignoring APKINDEX.84815163.tar.gz: No such file or directory
WARNING: Ignoring APKINDEX.24d64ab1.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  gcc (missing):
    required by: world[gcc]
  git (missing):
    required by: world[git]
  libc-dev (missing):
    required by: world[libc-dev]
  openssl-dev (missing):
    required by: world[openssl-dev]
/ #

**Comment by shlomiken** [comment]
ok i managed to continue - but there are several wrongs here.
need git + gcc to be able to install on alpine.
centos does not work - since it has openssl 1.1 and not 1.0 (like alpine does)
